services:
  service-theia-ide:
    build:
      context: ./service-theia-ide
      dockerfile: browser.Dockerfile
    container_name: service-theia-ide
    restart: always
    volumes:
      - ./projects:/home/project
    ports:
      - 3000:3000

  service-prefect-server:
    build:
      context: ./service-prefect
      dockerfile: Dockerfile
    container_name: service-prefect-server
    restart: always
    volumes:
      - scc-prefect:/root/.prefect
      - ./projects:/home/project
    command: ["server", "start", "--host", "0.0.0.0"]
    ports:
      - 4200:4200

  service-prefect-worker:
    build:
      context: ./service-prefect
      dockerfile: Dockerfile
    container_name: service-prefect-worker
    restart: always
    volumes:
      - scc-prefect:/root/.prefect
      - ./projects:/home/project
    command: ["worker", "start", "--pool", "scc-process-pool"]
    depends_on:
      - service-prefect-server

  service-timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: service-timescaledb
    restart: always
    environment:
      POSTGRES_USER: scc
      POSTGRES_PASSWORD: scc123
      POSTGRES_DB: scc-db
    volumes:
      - scc-timescale_data:/var/lib/postgresql/data

volumes:
  scc-prefect:
  scc-timescale_data:
