services:
  service-theia-ide:
    build:
      context: ./service-theia-ide
      dockerfile: browser.Dockerfile
    container_name: service-theia-ide
    restart: always
    volumes:
      - ./projects:/home/project
    ports:
      - 3000:3000

  service-prefect:
    build:
      context: ./service-prefect
      dockerfile: Dockerfile
    container_name: service-prefect
    restart: always
    volumes:
      - scc-prefect:/root/.prefect
    ports:
      - 4200:4200

  service-timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: service-timescaledb
    restart: always
    environment:
      POSTGRES_USER: scc
      POSTGRES_PASSWORD: scc123
      POSTGRES_DB: scc-db
    volumes:
      - scc-timescale_data:/var/lib/postgresql/data

volumes:
  scc-prefect:
  scc-timescale_data:
