services:
  service-code-center-ide:
    build:
      context: ./service-code-center-ide
      dockerfile: browser.Dockerfile
    container_name: service-code-center-ide
    volumes:
      - conda_volume:/opt/conda/envs
      - ./projects:/home/project
    ports:
      - 3000:3000

  service-code-center-backend:
    build:
      context: ./service-code-center-backend
      dockerfile: Dockerfile
    container_name: service-code-center-backend
    volumes:
      - conda_volume:/opt/conda/envs
      - ./projects:/app/app/projects
    ports:
      - 8000:8000

  service-code-center-front-react:
    build:
      context: ./service-code-center-front-react
      dockerfile: Dockerfile
    ports:
      - "3001:80"

volumes:
  conda_volume:
